// src/lib/screens/Loading.svelte
<script lang="ts">
  import { app } from '../app.svelte'
  import Label from '../ui/Label.svelte'
  import Note from '../ui/Note.svelte'
  import ProgressBar from '../ui/ProgressBar.svelte'

  const pct = $derived(
    app.loadTotal ? Math.round((app.loaded / app.loadTotal) * 100) + '%' : '0%',
  )
</script>

<div style="padding-top:var(--space-8)">
  <Label>Loading guitar samples</Label>
  <h1 style="font-size:34px;margin:var(--space-2) 0 var(--space-4)">{pct}</h1>
  <ProgressBar {pct} />
  <Note style="margin-top:var(--space-3)">Fetched once, then cached for offline use.</Note>
</div>

// src/screens/Loading.tsx
import { Label, Note, ProgressBar } from '../ui/primitives'

export function Loading({ pct }: { pct: string }) {
  return (
    <div style={{ paddingTop: 'var(--space-8)' }}>
      <Label>Loading guitar samples</Label>
      <h1 style={{ fontSize: 34, margin: 'var(--space-2) 0 var(--space-4)' }}>{pct}</h1>
      <ProgressBar pct={pct} />
      <Note style={{ marginTop: 'var(--space-3)' }}>Fetched once, then cached for offline use.</Note>
    </div>
  )
}
